-- Asignacion de LABEL_CODE a valores permisibles (470 valores, 16 categorias)
-- Excluye: clinical_diagnosis, date_format, time_format y categorias ya codificadas
-- Ejecutar directamente sobre la BD de OpenSpecimen

-- anatomic_site (333)
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.abdomen_nos' WHERE public_id = 'anatomic_site' AND value = 'Abdomen, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.abdominal_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Abdominal esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.accessory_sinus_nos' WHERE public_id = 'anatomic_site' AND value = 'Accessory sinus, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.acoustic_nerve' WHERE public_id = 'anatomic_site' AND value = 'Acoustic nerve';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.adrenal_gland_nos' WHERE public_id = 'anatomic_site' AND value = 'Adrenal gland, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ampulla_of_vater' WHERE public_id = 'anatomic_site' AND value = 'Ampulla of Vater';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anal_canal' WHERE public_id = 'anatomic_site' AND value = 'Anal canal';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_2_3_of_tongue_nos' WHERE public_id = 'anatomic_site' AND value = 'Anterior 2/3 of tongue, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_floor_of_mouth' WHERE public_id = 'anatomic_site' AND value = 'Anterior floor of mouth';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_mediastinum' WHERE public_id = 'anatomic_site' AND value = 'Anterior mediastinum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_surface_of_epiglottis' WHERE public_id = 'anatomic_site' AND value = 'Anterior surface of epiglottis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_wall_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Anterior wall of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anterior_wall_of_nasopharynx' WHERE public_id = 'anatomic_site' AND value = 'Anterior wall of nasopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.anus_nos' WHERE public_id = 'anatomic_site' AND value = 'Anus, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.aortic_body_and_other_paraganglia' WHERE public_id = 'anatomic_site' AND value = 'Aortic body and other paraganglia';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.appendix' WHERE public_id = 'anatomic_site' AND value = 'Appendix';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ascending_colon' WHERE public_id = 'anatomic_site' AND value = 'Ascending colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.autonomic_nervous_system_nos' WHERE public_id = 'anatomic_site' AND value = 'Autonomic nervous system, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.axillary_tail_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Axillary tail of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.base_of_tongue_nos' WHERE public_id = 'anatomic_site' AND value = 'Base of tongue, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.biliary_tract_nos' WHERE public_id = 'anatomic_site' AND value = 'Biliary tract, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bladder_neck' WHERE public_id = 'anatomic_site' AND value = 'Bladder neck';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bladder_nos' WHERE public_id = 'anatomic_site' AND value = 'Bladder, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.blood' WHERE public_id = 'anatomic_site' AND value = 'Blood';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.body_of_pancreas' WHERE public_id = 'anatomic_site' AND value = 'Body of pancreas';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.body_of_penis' WHERE public_id = 'anatomic_site' AND value = 'Body of penis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.body_of_stomach' WHERE public_id = 'anatomic_site' AND value = 'Body of stomach';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bone_marrow' WHERE public_id = 'anatomic_site' AND value = 'Bone marrow';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bone_nos' WHERE public_id = 'anatomic_site' AND value = 'Bone, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bone_of_limb_nos' WHERE public_id = 'anatomic_site' AND value = 'Bone of limb, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.bones_of_skull_and_face_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Bones of skull and face and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.border_of_tongue' WHERE public_id = 'anatomic_site' AND value = 'Border of tongue';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.brain_nos' WHERE public_id = 'anatomic_site' AND value = 'Brain, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.brain_stem' WHERE public_id = 'anatomic_site' AND value = 'Brain stem';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.branchial_cleft' WHERE public_id = 'anatomic_site' AND value = 'Branchial cleft';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.breast_nos' WHERE public_id = 'anatomic_site' AND value = 'Breast, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.broad_ligament' WHERE public_id = 'anatomic_site' AND value = 'Broad ligament';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cardia_nos' WHERE public_id = 'anatomic_site' AND value = 'Cardia, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.carotid_body' WHERE public_id = 'anatomic_site' AND value = 'Carotid body';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cauda_equina' WHERE public_id = 'anatomic_site' AND value = 'Cauda equina';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cecum' WHERE public_id = 'anatomic_site' AND value = 'Cecum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.central_portion_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Central portion of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cerebellum_nos' WHERE public_id = 'anatomic_site' AND value = 'Cerebellum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cerebral_meninges' WHERE public_id = 'anatomic_site' AND value = 'Cerebral meninges';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cerebrum' WHERE public_id = 'anatomic_site' AND value = 'Cerebrum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cervical_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Cervical esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cervix_uteri' WHERE public_id = 'anatomic_site' AND value = 'Cervix uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cheek_mucosa' WHERE public_id = 'anatomic_site' AND value = 'Cheek mucosa';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.choroid' WHERE public_id = 'anatomic_site' AND value = 'Choroid';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ciliary_body' WHERE public_id = 'anatomic_site' AND value = 'Ciliary body';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.clitoris' WHERE public_id = 'anatomic_site' AND value = 'Clitoris';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cloacogenic_zone' WHERE public_id = 'anatomic_site' AND value = 'Cloacogenic zone';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.colon_nos' WHERE public_id = 'anatomic_site' AND value = 'Colon, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.commissure_of_lip' WHERE public_id = 'anatomic_site' AND value = 'Commissure of lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.conjunctiva' WHERE public_id = 'anatomic_site' AND value = 'Conjunctiva';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_nos' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_abdomen' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of abdomen';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_head_face_and_neck' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of head, face, and neck';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_lower_limb_and_hip' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of lower limb and hip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_pelvis' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of pelvis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_thorax' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of thorax';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_trunk_nos' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of trunk, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.connective_subcutaneous_and_other_soft_tissues_of_upper_limb_and_shoulder' WHERE public_id = 'anatomic_site' AND value = 'Connective, Subcutaneous and other Soft tissues of upper limb and shoulder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cornea_nos' WHERE public_id = 'anatomic_site' AND value = 'Cornea, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.corpus_uteri' WHERE public_id = 'anatomic_site' AND value = 'Corpus uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cortex_of_adrenal_gland' WHERE public_id = 'anatomic_site' AND value = 'Cortex of adrenal gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.cranial_nerve_nos' WHERE public_id = 'anatomic_site' AND value = 'Cranial nerve, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.craniopharyngeal_duct' WHERE public_id = 'anatomic_site' AND value = 'Craniopharyngeal duct';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.descended_testis' WHERE public_id = 'anatomic_site' AND value = 'Descended testis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.descending_colon' WHERE public_id = 'anatomic_site' AND value = 'Descending colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.dome_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Dome of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.dorsal_surface_of_tongue_nos' WHERE public_id = 'anatomic_site' AND value = 'Dorsal surface of tongue, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.duodenum' WHERE public_id = 'anatomic_site' AND value = 'Duodenum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.endocervix' WHERE public_id = 'anatomic_site' AND value = 'Endocervix';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.endocrine_gland_nos' WHERE public_id = 'anatomic_site' AND value = 'Endocrine gland, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.endometrium' WHERE public_id = 'anatomic_site' AND value = 'Endometrium';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.epididymis' WHERE public_id = 'anatomic_site' AND value = 'Epididymis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.esophagus_nos' WHERE public_id = 'anatomic_site' AND value = 'Esophagus, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ethmoid_sinus' WHERE public_id = 'anatomic_site' AND value = 'Ethmoid sinus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.exocervix' WHERE public_id = 'anatomic_site' AND value = 'Exocervix';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.external_ear' WHERE public_id = 'anatomic_site' AND value = 'External ear';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.external_lip_nos' WHERE public_id = 'anatomic_site' AND value = 'External lip, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.external_lower_lip' WHERE public_id = 'anatomic_site' AND value = 'External lower lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.external_upper_lip' WHERE public_id = 'anatomic_site' AND value = 'External upper lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.extrahepatic_bile_duct' WHERE public_id = 'anatomic_site' AND value = 'Extrahepatic bile duct';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.eye_and_adnexa' WHERE public_id = 'anatomic_site' AND value = 'EYE AND ADNEXA';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.eye_nos' WHERE public_id = 'anatomic_site' AND value = 'Eye, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.eyelid' WHERE public_id = 'anatomic_site' AND value = 'Eyelid';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.fallopian_tube' WHERE public_id = 'anatomic_site' AND value = 'Fallopian tube';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.female_genital_tract_nos' WHERE public_id = 'anatomic_site' AND value = 'Female genital tract, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.floor_of_mouth_nos' WHERE public_id = 'anatomic_site' AND value = 'Floor of mouth, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.frontal_lobe' WHERE public_id = 'anatomic_site' AND value = 'Frontal lobe';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.frontal_sinus' WHERE public_id = 'anatomic_site' AND value = 'Frontal sinus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.fundus_of_stomach' WHERE public_id = 'anatomic_site' AND value = 'Fundus of stomach';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.fundus_uteri' WHERE public_id = 'anatomic_site' AND value = 'Fundus uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.gallbladder' WHERE public_id = 'anatomic_site' AND value = 'Gallbladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.gastric_antrum' WHERE public_id = 'anatomic_site' AND value = 'Gastric antrum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.gastrointestinal_tract_nos' WHERE public_id = 'anatomic_site' AND value = 'Gastrointestinal tract, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.glans_penis' WHERE public_id = 'anatomic_site' AND value = 'Glans penis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.glottis' WHERE public_id = 'anatomic_site' AND value = 'Glottis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.greater_curvature_of_stomach_nos' WHERE public_id = 'anatomic_site' AND value = 'Greater curvature of stomach, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.gum_nos' WHERE public_id = 'anatomic_site' AND value = 'Gum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.hard_palate' WHERE public_id = 'anatomic_site' AND value = 'Hard palate';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.head_face_or_neck_nos' WHERE public_id = 'anatomic_site' AND value = 'Head, face or neck, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.head_of_pancreas' WHERE public_id = 'anatomic_site' AND value = 'Head of pancreas';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.heart' WHERE public_id = 'anatomic_site' AND value = 'Heart';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.hematopoietic_system_nos' WHERE public_id = 'anatomic_site' AND value = 'Hematopoietic system, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.hepatic_flexure_of_colon' WHERE public_id = 'anatomic_site' AND value = 'Hepatic flexure of colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.hypopharyngeal_aspect_of_aryepiglottic_fold' WHERE public_id = 'anatomic_site' AND value = 'Hypopharyngeal aspect of aryepiglottic fold';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.hypopharynx_nos' WHERE public_id = 'anatomic_site' AND value = 'Hypopharynx, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ileum' WHERE public_id = 'anatomic_site' AND value = 'Ileum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ill_defined_sites_within_respiratory_system' WHERE public_id = 'anatomic_site' AND value = 'Ill-defined sites within respiratory system';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.intestinal_tract_nos' WHERE public_id = 'anatomic_site' AND value = 'Intestinal tract, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.intra_abdominal_lymph_nodes' WHERE public_id = 'anatomic_site' AND value = 'Intra-abdominal lymph nodes';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.intrahepatic_bile_duct' WHERE public_id = 'anatomic_site' AND value = 'Intrahepatic bile duct';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.intrathoracic_lymph_nodes' WHERE public_id = 'anatomic_site' AND value = 'Intrathoracic lymph nodes';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.islets_of_langerhans' WHERE public_id = 'anatomic_site' AND value = 'Islets of Langerhans';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.isthmus_uteri' WHERE public_id = 'anatomic_site' AND value = 'Isthmus uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.jejunum' WHERE public_id = 'anatomic_site' AND value = 'Jejunum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.kidney_nos' WHERE public_id = 'anatomic_site' AND value = 'Kidney, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.labium_majus' WHERE public_id = 'anatomic_site' AND value = 'Labium majus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.labium_minus' WHERE public_id = 'anatomic_site' AND value = 'Labium minus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lacrimal_gland' WHERE public_id = 'anatomic_site' AND value = 'Lacrimal gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.laryngeal_cartilage' WHERE public_id = 'anatomic_site' AND value = 'Laryngeal cartilage';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.laryngopharynx' WHERE public_id = 'anatomic_site' AND value = 'Laryngopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.larynx_nos' WHERE public_id = 'anatomic_site' AND value = 'Larynx, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lateral_floor_of_mouth' WHERE public_id = 'anatomic_site' AND value = 'Lateral floor of mouth';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lateral_wall_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Lateral wall of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lateral_wall_of_nasopharynx' WHERE public_id = 'anatomic_site' AND value = 'Lateral wall of nasopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lateral_wall_of_oropharynx' WHERE public_id = 'anatomic_site' AND value = 'Lateral wall of oropharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lesser_curvature_of_stomach_nos' WHERE public_id = 'anatomic_site' AND value = 'Lesser curvature of stomach, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lingual_tonsil' WHERE public_id = 'anatomic_site' AND value = 'Lingual tonsil';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lip_nos' WHERE public_id = 'anatomic_site' AND value = 'Lip, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.liver' WHERE public_id = 'anatomic_site' AND value = 'Liver';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.long_bones_of_lower_limb_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Long bones of lower limb and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.long_bones_of_upper_limb_scapula_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Long bones of upper limb, scapula and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_gum' WHERE public_id = 'anatomic_site' AND value = 'Lower gum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_inner_quadrant_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Lower-inner quadrant of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_limb_nos' WHERE public_id = 'anatomic_site' AND value = 'Lower limb, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_lobe_lung' WHERE public_id = 'anatomic_site' AND value = 'Lower lobe, lung';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_outer_quadrant_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Lower-outer quadrant of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lower_third_of_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Lower third of esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lung_nos' WHERE public_id = 'anatomic_site' AND value = 'Lung, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lymph_node_nos' WHERE public_id = 'anatomic_site' AND value = 'Lymph node, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lymph_nodes_of_axilla_or_arm' WHERE public_id = 'anatomic_site' AND value = 'Lymph nodes of axilla or arm';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lymph_nodes_of_head_face_and_neck' WHERE public_id = 'anatomic_site' AND value = 'Lymph nodes of head, face and neck';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lymph_nodes_of_inguinal_region_or_leg' WHERE public_id = 'anatomic_site' AND value = 'Lymph nodes of inguinal region or leg';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.lymph_nodes_of_multiple_regions' WHERE public_id = 'anatomic_site' AND value = 'Lymph nodes of multiple regions';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.main_bronchus' WHERE public_id = 'anatomic_site' AND value = 'Main bronchus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.major_salivary_gland_nos' WHERE public_id = 'anatomic_site' AND value = 'Major salivary gland, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.male_genital_organs_nos' WHERE public_id = 'anatomic_site' AND value = 'Male genital organs, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mandible' WHERE public_id = 'anatomic_site' AND value = 'Mandible';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.maxillary_sinus' WHERE public_id = 'anatomic_site' AND value = 'Maxillary sinus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.meckel_s_diverticulum' WHERE public_id = 'anatomic_site' AND value = 'Meckel''s diverticulum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mediastinum_nos' WHERE public_id = 'anatomic_site' AND value = 'Mediastinum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.medulla_of_adrenal_gland' WHERE public_id = 'anatomic_site' AND value = 'Medulla of adrenal gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.meninges_nos' WHERE public_id = 'anatomic_site' AND value = 'Meninges, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.middle_ear' WHERE public_id = 'anatomic_site' AND value = 'Middle ear';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.middle_lobe_lung' WHERE public_id = 'anatomic_site' AND value = 'Middle lobe, lung';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.middle_third_of_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Middle third of esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mouth_nos' WHERE public_id = 'anatomic_site' AND value = 'Mouth, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mucosa_of_lip_nos' WHERE public_id = 'anatomic_site' AND value = 'Mucosa of lip, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mucosa_of_lower_lip' WHERE public_id = 'anatomic_site' AND value = 'Mucosa of lower lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.mucosa_of_upper_lip' WHERE public_id = 'anatomic_site' AND value = 'Mucosa of upper lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.myometrium' WHERE public_id = 'anatomic_site' AND value = 'Myometrium';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.nasal_cavity' WHERE public_id = 'anatomic_site' AND value = 'Nasal cavity';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.nasopharynx_nos' WHERE public_id = 'anatomic_site' AND value = 'Nasopharynx, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.nervous_system_nos' WHERE public_id = 'anatomic_site' AND value = 'Nervous system, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.nipple' WHERE public_id = 'anatomic_site' AND value = 'Nipple';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.not_specified' WHERE public_id = 'anatomic_site' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.occipital_lobe' WHERE public_id = 'anatomic_site' AND value = 'Occipital lobe';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.olfactory_nerve' WHERE public_id = 'anatomic_site' AND value = 'Olfactory nerve';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.optic_nerve' WHERE public_id = 'anatomic_site' AND value = 'Optic nerve';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.orbit_nos' WHERE public_id = 'anatomic_site' AND value = 'Orbit, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.oropharynx_nos' WHERE public_id = 'anatomic_site' AND value = 'Oropharynx, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.other_ill_defined_sites' WHERE public_id = 'anatomic_site' AND value = 'Other ill-defined sites';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.other_specified_parts_of_female_genital_organs' WHERE public_id = 'anatomic_site' AND value = 'Other specified parts of female genital organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.other_specified_parts_of_male_genital_organs' WHERE public_id = 'anatomic_site' AND value = 'Other specified parts of male genital organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.other_specified_parts_of_pancreas' WHERE public_id = 'anatomic_site' AND value = 'Other specified parts of pancreas';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ovary' WHERE public_id = 'anatomic_site' AND value = 'Ovary';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_accessory_sinuses' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of accessory sinuses';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_biliary_tract' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of biliary tract';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_bones_joints_and_articular_cartilage' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of bones, joints and articular cartilage';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_bones_joints_and_articular_cartilage_of_limbs' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of bones, joints and articular cartilage of limbs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_brain' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of brain';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_brain_and_central_nervous_system' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of brain and central nervous system';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_cervix_uteri' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of cervix uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_colon' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_connective_subcutaneous_and_other_soft_tissues' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of connective, subcutaneous and other soft tissues';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_corpus_uteri' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of corpus uteri';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_digestive_system' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of digestive system';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_endocrine_glands_and_related_structures' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of endocrine glands and related structures';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_eye_and_adnexa' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of eye and adnexa';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_female_genital_organs' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of female genital organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_floor_of_mouth' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of floor of mouth';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_heart_mediastinum_and_pleura' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of heart, mediastinum and pleura';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_hypopharynx' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of hypopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_ill_defined_sites' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of ill-defined sites';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_larynx' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of larynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_lip' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of lip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_lip_oral_cavity_and_pharynx' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of lip, oral cavity and pharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_lung' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of lung';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_major_salivary_glands' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of major salivary glands';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_male_genital_organs' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of male genital organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_nasopharynx' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of nasopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_oropharynx' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of oropharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_other_and_unspecified_parts_of_mouth' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of other and unspecified parts of mouth';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_palate' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of palate';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_pancreas' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of pancreas';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_penis' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of penis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_peripheral_nerves_and_autonomic_nervous_system' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of peripheral nerves and autonomic nervous system';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_rectum_anus_and_anal_canal' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of rectum, anus and anal canal';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_respiratory_system_and_intrathoracic_organs' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of respiratory system and intrathoracic organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_retroperitoneum_and_peritoneum' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of retroperitoneum and peritoneum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_skin' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of skin';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_small_intestine' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of small intestine';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_stomach' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of stomach';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_tongue' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of tongue';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_tonsil' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of tonsil';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_urinary_organs' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of urinary organs';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.overlapping_lesion_of_vulva' WHERE public_id = 'anatomic_site' AND value = 'Overlapping lesion of vulva';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.palate_nos' WHERE public_id = 'anatomic_site' AND value = 'Palate, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pancreas_nos' WHERE public_id = 'anatomic_site' AND value = 'Pancreas, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pancreatic_duct' WHERE public_id = 'anatomic_site' AND value = 'Pancreatic duct';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.parametrium' WHERE public_id = 'anatomic_site' AND value = 'Parametrium';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.parathyroid_gland' WHERE public_id = 'anatomic_site' AND value = 'Parathyroid gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.paraurethral_gland' WHERE public_id = 'anatomic_site' AND value = 'Paraurethral gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.parietal_lobe' WHERE public_id = 'anatomic_site' AND value = 'Parietal lobe';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.parotid_gland' WHERE public_id = 'anatomic_site' AND value = 'Parotid gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pelvic_bones_sacrum_coccyx_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Pelvic bones, Sacrum, Coccyx and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pelvic_lymph_nodes' WHERE public_id = 'anatomic_site' AND value = 'Pelvic lymph nodes';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pelvis_nos' WHERE public_id = 'anatomic_site' AND value = 'Pelvis, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.penis_nos' WHERE public_id = 'anatomic_site' AND value = 'Penis, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_abdomen' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of abdomen';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_head_face_and_neck' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of head, face, and neck';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_lower_limb_and_hip' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of lower limb and hip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_pelvis' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of pelvis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_thorax' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of thorax';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_trunk_nos' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of trunk, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peripheral_nerves_and_autonomic_nervous_system_of_upper_limb_and_shoulder' WHERE public_id = 'anatomic_site' AND value = 'Peripheral nerves and Autonomic nervous system of upper limb and shoulder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.peritoneum_nos' WHERE public_id = 'anatomic_site' AND value = 'Peritoneum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pharynx_nos' WHERE public_id = 'anatomic_site' AND value = 'Pharynx, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pineal_gland' WHERE public_id = 'anatomic_site' AND value = 'Pineal gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pituitary_gland' WHERE public_id = 'anatomic_site' AND value = 'Pituitary gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.placenta' WHERE public_id = 'anatomic_site' AND value = 'Placenta';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pleura_nos' WHERE public_id = 'anatomic_site' AND value = 'Pleura, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.postcricoid_region' WHERE public_id = 'anatomic_site' AND value = 'Postcricoid region';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.posterior_mediastinum' WHERE public_id = 'anatomic_site' AND value = 'Posterior mediastinum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.posterior_wall_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Posterior wall of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.posterior_wall_of_hypopharynx' WHERE public_id = 'anatomic_site' AND value = 'Posterior wall of hypopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.posterior_wall_of_nasopharynx' WHERE public_id = 'anatomic_site' AND value = 'Posterior wall of nasopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.posterior_wall_of_oropharynx' WHERE public_id = 'anatomic_site' AND value = 'Posterior wall of oropharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.prepuce' WHERE public_id = 'anatomic_site' AND value = 'Prepuce';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.prostate_gland' WHERE public_id = 'anatomic_site' AND value = 'Prostate gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pylorus' WHERE public_id = 'anatomic_site' AND value = 'Pylorus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.pyriform_sinus' WHERE public_id = 'anatomic_site' AND value = 'Pyriform sinus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.rectosigmoid_junction' WHERE public_id = 'anatomic_site' AND value = 'Rectosigmoid junction';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.rectum_nos' WHERE public_id = 'anatomic_site' AND value = 'Rectum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.renal_pelvis' WHERE public_id = 'anatomic_site' AND value = 'Renal pelvis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.reticuloendothelial_system_nos' WHERE public_id = 'anatomic_site' AND value = 'Reticuloendothelial system, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.retina' WHERE public_id = 'anatomic_site' AND value = 'Retina';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.retromolar_area' WHERE public_id = 'anatomic_site' AND value = 'Retromolar area';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.retroperitoneum' WHERE public_id = 'anatomic_site' AND value = 'Retroperitoneum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.rib_sternum_clavicle_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Rib, Sternum, Clavicle and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.round_ligament' WHERE public_id = 'anatomic_site' AND value = 'Round ligament';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.scrotum_nos' WHERE public_id = 'anatomic_site' AND value = 'Scrotum, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.short_bones_of_lower_limb_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Short bones of lower limb and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.short_bones_of_upper_limb_and_associated_joints' WHERE public_id = 'anatomic_site' AND value = 'Short bones of upper limb and associated joints';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.sigmoid_colon' WHERE public_id = 'anatomic_site' AND value = 'Sigmoid colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_nos' WHERE public_id = 'anatomic_site' AND value = 'Skin, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_lip_nos' WHERE public_id = 'anatomic_site' AND value = 'Skin of lip, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_lower_limb_and_hip' WHERE public_id = 'anatomic_site' AND value = 'Skin of lower limb and hip';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_other_and_unspecified_parts_of_face' WHERE public_id = 'anatomic_site' AND value = 'Skin of other and unspecified parts of face';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_scalp_and_neck' WHERE public_id = 'anatomic_site' AND value = 'Skin of scalp and neck';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_trunk' WHERE public_id = 'anatomic_site' AND value = 'Skin of trunk';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.skin_of_upper_limb_and_shoulder' WHERE public_id = 'anatomic_site' AND value = 'Skin of upper limb and shoulder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.small_intestine_nos' WHERE public_id = 'anatomic_site' AND value = 'Small intestine, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.soft_palate_nos' WHERE public_id = 'anatomic_site' AND value = 'Soft palate, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.specified_parts_of_peritoneum' WHERE public_id = 'anatomic_site' AND value = 'Specified parts of peritoneum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.spermatic_cord' WHERE public_id = 'anatomic_site' AND value = 'Spermatic cord';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.sphenoid_sinus' WHERE public_id = 'anatomic_site' AND value = 'Sphenoid sinus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.spinal_cord' WHERE public_id = 'anatomic_site' AND value = 'Spinal cord';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.spinal_meninges' WHERE public_id = 'anatomic_site' AND value = 'Spinal meninges';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.spleen' WHERE public_id = 'anatomic_site' AND value = 'Spleen';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.splenic_flexure_of_colon' WHERE public_id = 'anatomic_site' AND value = 'Splenic flexure of colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.stomach_nos' WHERE public_id = 'anatomic_site' AND value = 'Stomach, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.subglottis' WHERE public_id = 'anatomic_site' AND value = 'Subglottis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.sublingual_gland' WHERE public_id = 'anatomic_site' AND value = 'Sublingual gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.submandibular_gland' WHERE public_id = 'anatomic_site' AND value = 'Submandibular gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.superior_wall_of_nasopharynx' WHERE public_id = 'anatomic_site' AND value = 'Superior wall of nasopharynx';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.supraglottis' WHERE public_id = 'anatomic_site' AND value = 'Supraglottis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.tail_of_pancreas' WHERE public_id = 'anatomic_site' AND value = 'Tail of pancreas';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.temporal_lobe' WHERE public_id = 'anatomic_site' AND value = 'Temporal lobe';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.testis_nos' WHERE public_id = 'anatomic_site' AND value = 'Testis, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.thoracic_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Thoracic esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.thorax_nos' WHERE public_id = 'anatomic_site' AND value = 'Thorax, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.thymus' WHERE public_id = 'anatomic_site' AND value = 'Thymus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.thyroid_gland' WHERE public_id = 'anatomic_site' AND value = 'Thyroid gland';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.tongue_nos' WHERE public_id = 'anatomic_site' AND value = 'Tongue, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.tonsil_nos' WHERE public_id = 'anatomic_site' AND value = 'Tonsil, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.tonsillar_fossa' WHERE public_id = 'anatomic_site' AND value = 'Tonsillar fossa';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.tonsillar_pillar' WHERE public_id = 'anatomic_site' AND value = 'Tonsillar pillar';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.trachea' WHERE public_id = 'anatomic_site' AND value = 'Trachea';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.transverse_colon' WHERE public_id = 'anatomic_site' AND value = 'Transverse colon';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.trigone_of_bladder' WHERE public_id = 'anatomic_site' AND value = 'Trigone of bladder';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.undescended_testis' WHERE public_id = 'anatomic_site' AND value = 'Undescended testis';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.unknown_primary_site' WHERE public_id = 'anatomic_site' AND value = 'UNKNOWN PRIMARY SITE';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_gum' WHERE public_id = 'anatomic_site' AND value = 'Upper gum';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_inner_quadrant_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Upper-inner quadrant of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_limb_nos' WHERE public_id = 'anatomic_site' AND value = 'Upper limb, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_lobe_lung' WHERE public_id = 'anatomic_site' AND value = 'Upper lobe, lung';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_outer_quadrant_of_breast' WHERE public_id = 'anatomic_site' AND value = 'Upper-outer quadrant of breast';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_respiratory_tract_nos' WHERE public_id = 'anatomic_site' AND value = 'Upper respiratory tract, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.upper_third_of_esophagus' WHERE public_id = 'anatomic_site' AND value = 'Upper third of esophagus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.urachus' WHERE public_id = 'anatomic_site' AND value = 'Urachus';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ureter' WHERE public_id = 'anatomic_site' AND value = 'Ureter';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ureteric_orifice' WHERE public_id = 'anatomic_site' AND value = 'Ureteric orifice';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.urethra' WHERE public_id = 'anatomic_site' AND value = 'Urethra';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.urinary_system_nos' WHERE public_id = 'anatomic_site' AND value = 'Urinary system, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.uterine_adnexa' WHERE public_id = 'anatomic_site' AND value = 'Uterine adnexa';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.uterus_nos' WHERE public_id = 'anatomic_site' AND value = 'Uterus, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.uvula' WHERE public_id = 'anatomic_site' AND value = 'Uvula';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.vagina_nos' WHERE public_id = 'anatomic_site' AND value = 'Vagina, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.vallecula' WHERE public_id = 'anatomic_site' AND value = 'Vallecula';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ventral_surface_of_tongue_nos' WHERE public_id = 'anatomic_site' AND value = 'Ventral surface of tongue, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.ventricle_nos' WHERE public_id = 'anatomic_site' AND value = 'Ventricle, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.vertebral_column' WHERE public_id = 'anatomic_site' AND value = 'Vertebral column';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.vestibule_of_mouth' WHERE public_id = 'anatomic_site' AND value = 'Vestibule of mouth';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.vulva_nos' WHERE public_id = 'anatomic_site' AND value = 'Vulva, NOS';
UPDATE catissue_permissible_value SET label_code = 'pvs.anatomic_site.waldeyer_s_ring' WHERE public_id = 'anatomic_site' AND value = 'Waldeyer''s ring';

-- collection_container (11)
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.acd_vacutainer' WHERE public_id = 'collection_container' AND value = 'ACD Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.citrate_vacutainer' WHERE public_id = 'collection_container' AND value = 'Citrate Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.cpt' WHERE public_id = 'collection_container' AND value = 'CPT';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.edta_vacutainer' WHERE public_id = 'collection_container' AND value = 'EDTA Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.heparin_vacutainer' WHERE public_id = 'collection_container' AND value = 'Heparin Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.no_additive_vacutainer' WHERE public_id = 'collection_container' AND value = 'No Additive Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.not_specified' WHERE public_id = 'collection_container' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.paxgene' WHERE public_id = 'collection_container' AND value = 'Paxgene';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.serum_separator_vacutainer' WHERE public_id = 'collection_container' AND value = 'Serum Separator Vacutainer';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.sterile_specimen_container' WHERE public_id = 'collection_container' AND value = 'Sterile Specimen Container';
UPDATE catissue_permissible_value SET label_code = 'pvs.collection_container.streck' WHERE public_id = 'collection_container' AND value = 'Streck';

-- consent_response (5)
UPDATE catissue_permissible_value SET label_code = 'pvs.consent_response.no' WHERE public_id = 'consent_response' AND value = 'No';
UPDATE catissue_permissible_value SET label_code = 'pvs.consent_response.none' WHERE public_id = 'consent_response' AND value = 'None';
UPDATE catissue_permissible_value SET label_code = 'pvs.consent_response.not_specified' WHERE public_id = 'consent_response' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.consent_response.withdrawn' WHERE public_id = 'consent_response' AND value = 'Withdrawn';
UPDATE catissue_permissible_value SET label_code = 'pvs.consent_response.yes' WHERE public_id = 'consent_response' AND value = 'Yes';

-- embedding_medium (7)
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.freezing_media_not_specified' WHERE public_id = 'embedding_medium' AND value = 'Freezing Media, Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.low_melting_point_paraffin' WHERE public_id = 'embedding_medium' AND value = 'Low Melting Point Paraffin';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.not_specified' WHERE public_id = 'embedding_medium' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.optimal_cutting_temperature_media' WHERE public_id = 'embedding_medium' AND value = 'Optimal Cutting Temperature Media';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.paraffin' WHERE public_id = 'embedding_medium' AND value = 'Paraffin';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.plastic' WHERE public_id = 'embedding_medium' AND value = 'Plastic';
UPDATE catissue_permissible_value SET label_code = 'pvs.embedding_medium.resin' WHERE public_id = 'embedding_medium' AND value = 'Resin';

-- ethnicity (4)
UPDATE catissue_permissible_value SET label_code = 'pvs.ethnicity.hispanic_or_latino' WHERE public_id = 'ethnicity' AND value = 'Hispanic or Latino';
UPDATE catissue_permissible_value SET label_code = 'pvs.ethnicity.not_hispanic_or_latino' WHERE public_id = 'ethnicity' AND value = 'Not Hispanic or Latino';
UPDATE catissue_permissible_value SET label_code = 'pvs.ethnicity.not_reported' WHERE public_id = 'ethnicity' AND value = 'Not Reported';
UPDATE catissue_permissible_value SET label_code = 'pvs.ethnicity.unknown' WHERE public_id = 'ethnicity' AND value = 'Unknown';

-- fixation_type (9)
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.bouin_s' WHERE public_id = 'fixation_type' AND value = 'Bouin''s';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.ethanol_70' WHERE public_id = 'fixation_type' AND value = 'Ethanol, 70%';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.formaldehyde' WHERE public_id = 'fixation_type' AND value = 'Formaldehyde';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.methacarn' WHERE public_id = 'fixation_type' AND value = 'Methacarn';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.methanol' WHERE public_id = 'fixation_type' AND value = 'Methanol';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.neutral_buffered_formalin' WHERE public_id = 'fixation_type' AND value = 'Neutral Buffered Formalin';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.not_specified' WHERE public_id = 'fixation_type' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.rnalater' WHERE public_id = 'fixation_type' AND value = 'RNALater';
UPDATE catissue_permissible_value SET label_code = 'pvs.fixation_type.um_fix' WHERE public_id = 'fixation_type' AND value = 'UM-Fix';

-- frozen_method (9)
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.aerosol_spray' WHERE public_id = 'frozen_method' AND value = 'Aerosol Spray';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.cryobath' WHERE public_id = 'frozen_method' AND value = 'Cryobath';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.cryostat' WHERE public_id = 'frozen_method' AND value = 'Cryostat';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.dry_ice' WHERE public_id = 'frozen_method' AND value = 'Dry Ice';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.dry_ice_hydrocarbon_slurry' WHERE public_id = 'frozen_method' AND value = 'Dry Ice / Hydrocarbon Slurry';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.liquid_nitrogen' WHERE public_id = 'frozen_method' AND value = 'Liquid Nitrogen';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.liquid_nitrogen_isopentane' WHERE public_id = 'frozen_method' AND value = 'Liquid Nitrogen / Isopentane';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.liquid_nitrogen_vapor' WHERE public_id = 'frozen_method' AND value = 'Liquid Nitrogen Vapor';
UPDATE catissue_permissible_value SET label_code = 'pvs.frozen_method.not_specified' WHERE public_id = 'frozen_method' AND value = 'Not Specified';

-- histological_quality (5)
UPDATE catissue_permissible_value SET label_code = 'pvs.histological_quality.excellent_definable_nuclear_detail' WHERE public_id = 'histological_quality' AND value = 'Excellent- Definable Nuclear Detail';
UPDATE catissue_permissible_value SET label_code = 'pvs.histological_quality.fair_definable_tissue_architecture' WHERE public_id = 'histological_quality' AND value = 'Fair- Definable Tissue Architecture';
UPDATE catissue_permissible_value SET label_code = 'pvs.histological_quality.good_definable_cellular_detail' WHERE public_id = 'histological_quality' AND value = 'Good- Definable Cellular Detail';
UPDATE catissue_permissible_value SET label_code = 'pvs.histological_quality.not_specified' WHERE public_id = 'histological_quality' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.histological_quality.poor_no_definable_features' WHERE public_id = 'histological_quality' AND value = 'Poor- No Definable Features';

-- missed_visit_reason (9)
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.beyond_processing_time' WHERE public_id = 'missed_visit_reason' AND value = 'Beyond processing time';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.insufficient_sample_collected_available' WHERE public_id = 'missed_visit_reason' AND value = 'Insufficient sample collected / available';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.laboratory_error' WHERE public_id = 'missed_visit_reason' AND value = 'Laboratory error';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.patient_declined_collection' WHERE public_id = 'missed_visit_reason' AND value = 'Patient declined collection';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.patient_declined_consent' WHERE public_id = 'missed_visit_reason' AND value = 'Patient declined consent';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.poor_sample_quality' WHERE public_id = 'missed_visit_reason' AND value = 'Poor sample quality';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.sample_damaged' WHERE public_id = 'missed_visit_reason' AND value = 'Sample damaged';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.sample_not_collected_by_clinic_clinic_error' WHERE public_id = 'missed_visit_reason' AND value = 'Sample not collected by clinic / Clinic error';
UPDATE catissue_permissible_value SET label_code = 'pvs.missed_visit_reason.visit_cancelled' WHERE public_id = 'missed_visit_reason' AND value = 'Visit cancelled';

-- shipment_item_received_quality (2)
UPDATE catissue_permissible_value SET label_code = 'pvs.shipment_item_received_quality.acceptable' WHERE public_id = 'shipment_item_received_quality' AND value = 'Acceptable';
UPDATE catissue_permissible_value SET label_code = 'pvs.shipment_item_received_quality.unacceptable' WHERE public_id = 'shipment_item_received_quality' AND value = 'Unacceptable';

-- shipment_request_status (3)
UPDATE catissue_permissible_value SET label_code = 'pvs.shipment_request_status.approved' WHERE public_id = 'shipment_request_status' AND value = 'Approved';
UPDATE catissue_permissible_value SET label_code = 'pvs.shipment_request_status.fulfilled' WHERE public_id = 'shipment_request_status' AND value = 'Fulfilled';
UPDATE catissue_permissible_value SET label_code = 'pvs.shipment_request_status.in_progress' WHERE public_id = 'shipment_request_status' AND value = 'In Progress';

-- site_type (4)
UPDATE catissue_permissible_value SET label_code = 'pvs.site_type.collection_site' WHERE public_id = 'site_type' AND value = 'Collection Site';
UPDATE catissue_permissible_value SET label_code = 'pvs.site_type.laboratory' WHERE public_id = 'site_type' AND value = 'Laboratory';
UPDATE catissue_permissible_value SET label_code = 'pvs.site_type.not_specified' WHERE public_id = 'site_type' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.site_type.repository' WHERE public_id = 'site_type' AND value = 'Repository';

-- specimen_biohazard (5)
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_biohazard.hepatitis_a' WHERE public_id = 'specimen_biohazard' AND value = 'Hepatitis A';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_biohazard.hepatitis_b' WHERE public_id = 'specimen_biohazard' AND value = 'Hepatitis B';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_biohazard.hepatitis_c' WHERE public_id = 'specimen_biohazard' AND value = 'Hepatitis C';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_biohazard.hiv' WHERE public_id = 'specimen_biohazard' AND value = 'HIV';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_biohazard.tuberculosis' WHERE public_id = 'specimen_biohazard' AND value = 'Tuberculosis';

-- specimen_dispose_reason (6)
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.damaged' WHERE public_id = 'specimen_dispose_reason' AND value = 'Damaged';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.destroyed' WHERE public_id = 'specimen_dispose_reason' AND value = 'Destroyed';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.distributed' WHERE public_id = 'specimen_dispose_reason' AND value = 'Distributed';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.not_specified' WHERE public_id = 'specimen_dispose_reason' AND value = 'Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.pooled' WHERE public_id = 'specimen_dispose_reason' AND value = 'Pooled';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_dispose_reason.processed' WHERE public_id = 'specimen_dispose_reason' AND value = 'Processed';

-- specimen_type (53)
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.amniotic_fluid' WHERE public_id = 'specimen_type' AND value = 'Amniotic Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.bile' WHERE public_id = 'specimen_type' AND value = 'Bile';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.body_cavity_fluid' WHERE public_id = 'specimen_type' AND value = 'Body Cavity Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.bone_marrow_plasma' WHERE public_id = 'specimen_type' AND value = 'Bone Marrow Plasma';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.buffy_coat' WHERE public_id = 'specimen_type' AND value = 'Buffy Coat';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.cdna' WHERE public_id = 'specimen_type' AND value = 'cDNA';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.cell' WHERE public_id = 'specimen_type' AND value = 'Cell';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.cell_not_specified' WHERE public_id = 'specimen_type' AND value = 'Cell - Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.cerebrospinal_fluid' WHERE public_id = 'specimen_type' AND value = 'Cerebrospinal Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.cryopreserved_cells' WHERE public_id = 'specimen_type' AND value = 'Cryopreserved Cells';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.ctdna' WHERE public_id = 'specimen_type' AND value = 'ctDNA';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.dna' WHERE public_id = 'specimen_type' AND value = 'DNA';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.feces' WHERE public_id = 'specimen_type' AND value = 'Feces';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fixed_cell_block' WHERE public_id = 'specimen_type' AND value = 'Fixed Cell Block';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fixed_tissue' WHERE public_id = 'specimen_type' AND value = 'Fixed Tissue';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fixed_tissue_block' WHERE public_id = 'specimen_type' AND value = 'Fixed Tissue Block';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fixed_tissue_slide' WHERE public_id = 'specimen_type' AND value = 'Fixed Tissue Slide';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fluid' WHERE public_id = 'specimen_type' AND value = 'Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fluid_not_specified' WHERE public_id = 'specimen_type' AND value = 'Fluid - Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.fresh_tissue' WHERE public_id = 'specimen_type' AND value = 'Fresh Tissue';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.frozen_cell_block' WHERE public_id = 'specimen_type' AND value = 'Frozen Cell Block';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.frozen_cell_pellet' WHERE public_id = 'specimen_type' AND value = 'Frozen Cell Pellet';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.frozen_tissue' WHERE public_id = 'specimen_type' AND value = 'Frozen Tissue';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.frozen_tissue_block' WHERE public_id = 'specimen_type' AND value = 'Frozen Tissue Block';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.frozen_tissue_slide' WHERE public_id = 'specimen_type' AND value = 'Frozen Tissue Slide';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.gastric_fluid' WHERE public_id = 'specimen_type' AND value = 'Gastric Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.lavage' WHERE public_id = 'specimen_type' AND value = 'Lavage';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.microdissected' WHERE public_id = 'specimen_type' AND value = 'Microdissected';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.milk' WHERE public_id = 'specimen_type' AND value = 'Milk';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.molecular' WHERE public_id = 'specimen_type' AND value = 'Molecular';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.molecular_not_specified' WHERE public_id = 'specimen_type' AND value = 'Molecular - Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.pbmc' WHERE public_id = 'specimen_type' AND value = 'PBMC';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.pericardial_fluid' WHERE public_id = 'specimen_type' AND value = 'Pericardial Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.plasma' WHERE public_id = 'specimen_type' AND value = 'Plasma';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.protein' WHERE public_id = 'specimen_type' AND value = 'protein';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.rna' WHERE public_id = 'specimen_type' AND value = 'RNA';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.rna_cytoplasmic' WHERE public_id = 'specimen_type' AND value = 'RNA, cytoplasmic';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.rna_nuclear' WHERE public_id = 'specimen_type' AND value = 'RNA, nuclear';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.rna_poly_a_enriched' WHERE public_id = 'specimen_type' AND value = 'RNA, poly-A enriched';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.saliva' WHERE public_id = 'specimen_type' AND value = 'Saliva';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.serum' WHERE public_id = 'specimen_type' AND value = 'Serum';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.slide' WHERE public_id = 'specimen_type' AND value = 'Slide';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.sputum' WHERE public_id = 'specimen_type' AND value = 'Sputum';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.sweat' WHERE public_id = 'specimen_type' AND value = 'Sweat';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.synovial_fluid' WHERE public_id = 'specimen_type' AND value = 'Synovial Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.tissue' WHERE public_id = 'specimen_type' AND value = 'Tissue';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.tissue_not_specified' WHERE public_id = 'specimen_type' AND value = 'Tissue - Not Specified';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.total_nucleic_acid' WHERE public_id = 'specimen_type' AND value = 'Total Nucleic Acid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.urine' WHERE public_id = 'specimen_type' AND value = 'Urine';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.vitreous_fluid' WHERE public_id = 'specimen_type' AND value = 'Vitreous Fluid';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.whole_blood' WHERE public_id = 'specimen_type' AND value = 'Whole Blood';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.whole_bone_marrow' WHERE public_id = 'specimen_type' AND value = 'Whole Bone Marrow';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_type.whole_genome_amplified_dna' WHERE public_id = 'specimen_type' AND value = 'Whole Genome Amplified DNA';

-- specimen_unit (5)
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_unit.cells' WHERE public_id = 'specimen_unit' AND value = 'Cells';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_unit.gm' WHERE public_id = 'specimen_unit' AND value = 'gm';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_unit.ml' WHERE public_id = 'specimen_unit' AND value = 'ml';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_unit.ug' WHERE public_id = 'specimen_unit' AND value = 'µg';
UPDATE catissue_permissible_value SET label_code = 'pvs.specimen_unit.ug_ml' WHERE public_id = 'specimen_unit' AND value = 'µg/ml';

COMMIT;
